#!/bin/bash

git add  `git status  | grep modified | awk '{print $2}'`
git commit -m "."

/usr/bin/expect << EOF
spawn git push origin master
expect  "Enter passphrase for key '/home/k/.ssh/id_rsa':"
send "K28lqp8bt"
EOF

